### ISSUE TITLE
Addon shows only the first 25 episodes of a season

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#482]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.6

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Windows
- OS version: Windows 10
- Kodi version number: 18.4

**Describe the bug**

If a season has more than 25 episodes the addon lists only the first 25 episodes, the rest are missing.
For example The Office season 5 (https://www.primevideo.com/detail/0IMOV8SHN2LIJE1SDHCIVVAYYS/) has 28 episodes. The prime video website actually lists 25 episodes, in order to get the rest I have to click a link at the bottom of the page (which adds "?episodeListSize=28" to the URL).

**Comment by Varstahl** [comment]
This should already be fixed. Can you try to refresh the season? It might just be a cache issue.

**Comment by Varstahl** [comment]
Unless Amazon broke it again (which is possible) it should be fixed since 542d21d893aedb1be3b64df67efe87351cf1235b, so 0.8.5+

**Comment by Paco8** [comment]
For some reason it doesn't work for me. I tried enabling and disabling all the pagination options and then refreshing the season, but it still shows only 25 episodes.

**Comment by Varstahl** [comment]
They might have removed the option, let me check.

**Comment by Varstahl** [comment]
@Paco8 does this link show you all the episodes? https://www.primevideo.com/detail/0IMOV8SHN2LIJE1SDHCIVVAYYS/?episodeListSize=999999999999

**Comment by Varstahl** [comment]
I can't seem to replicate this issue, on my end it is still fixed.
![Refresh](https://user-images.githubusercontent.com/284077/85947676-80561680-b94c-11ea-98a3-0b95d65bbdec.png)
![28 episodes](https://user-images.githubusercontent.com/284077/85947687-8946e800-b94c-11ea-8bcc-4be53a5dac62.png)

**Comment by Paco8** [comment]
> @Paco8 does this link show you all the episodes? https://www.primevideo.com/detail/0IMOV8SHN2LIJE1SDHCIVVAYYS/?episodeListSize=999999999999

Yes.

This is what I did: I removed the cache files. In the addon preferences I enabled pagination for the watchlist. Now I entered in "my space/shows" and wait and all shows appear. Now season 5 of the office has 28 episodes but the rest of seasons show 25. If I refresh season 5 it still shows 28 episodes, but if I refresh season 6 or 7 it shows 25 episodes (they have more than 25). Looks like the refresh option is not working.

**Comment by Varstahl** [comment]
I'll investigate if there's a regression in the refresh.

**Comment by Varstahl** [comment]
I've made sure that refs don't include episode length, removed episodes by hand, refresh still works. I'm sorry but I have no idea why it's not working for you.

One thing it's not clear though, you refreshed season 5 and that's ok, but did you refresh seasons 6 and 7 as well?

**Comment by Varstahl** [comment]
Can you send me the PVCP/PVDP files, so that I can take a look?

**Comment by Paco8** [comment]
I attach the files.

This is what I did step by step: I removed the PVCP/PVDP files. In the addon preferences the pagination is enabled for watchlist but the other pagination options are disabled. Season 5 is in my watchlist, but not the others.
After entering in my space/shows, season 5 has 28 episodes (correct), but season 6 and 7 have 25. If I refresh season 6 and 7 they still show 25 episodes. If I refresh season 5 it still shows 28 episodes.

[catalog-files.zip](https://github.com/Sandmann79/xbmc/files/4852428/catalog-files.zip)

**Comment by fabpolli** [comment]
Hi, I've aligned plugin with current repo version but error at url in issue #487 still present.
[AmazonVideoData.zip](https://github.com/Sandmann79/xbmc/files/4952810/AmazonVideoData.zip)
I've attached my pluging cache data for debug purpose

**Comment by Varstahl** [comment]
As mentioned in the #491 I'll run some more tests today, sorry for the wait guys.

**Comment by Varstahl** [comment]
Finally found this pesky bug. It goes way beyond the simple refresh, it's one nasty son of a gun. It's gonna take me a few hours to nail this and find a way to fix it, so I'll just finish this tomorrow.

**Comment by fabpolli** [comment]
I am happy to read this, any improvement of the addon is good news. I tried to help with my skills, but my poor knowledge of how the addon works has led me to edit a critical file, I hope to be more useful in the future.
I will be happy to try the fix when it is ready and placed in the repository, now on all of my devices I can see all episodies so when I will remove my fix and align addon to repo version I'll can test Your correction on Windows and on Raspberry Pi.

**Comment by Varstahl** [comment]
The main problem I understand so far is that things changed "a little bit" on their servers, so while everything technically still works *sometimes it doesn't on certain conditions*. I'm half tempted to brute-force and just add the 9999 to every single query and see if anything breaks, although there's a bit more stuff I need to take care of. In any case unless it's really bad, it should be ready today.

**Comment by Varstahl** [comment]
@fabpolli there's a few more things I need to check out but you can test this out with the [main branch](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test). This bug should definitely be squashed under a hydraulic press. Not elegant, but it works.

**Comment by fabpolli** [comment]
@Varstahl first turn of test on Windows...passed!  I will test on Raspberry in the weekend or, maybe, this evening

**Comment by fabpolli** [comment]
Sorry for late answer, very busy days... Tested also on Raspberry Pi 4 with Kodi on LibreELEC, works like a charms!
