### ISSUE TITLE
Unknown error after login attempt - 'The soupsieve package is not installed. CSS selectors cannot be used.'

### ISSUE THREAD

**Issue by cptncrnch** [Sandmann79/xbmc#553]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.1

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: BCM2835, Raspberry Pi 3 Model B Rev 1.2
- OS version: OSMC 2020.11-1
- Kodi version number: 18.9

**Upload Logs**

https://pastebin.com/Vn80ejgs

**Describe the bug**

At first, after opening the Amazon Video application, opening the Watchlist and choosing Movies or Television showed an error saying it was not logged in. The Connection settings showed I was still logged in so the login credentials and cookies were cleared. Attempting to log back in would not work and an unknown error would display. The logs show an error that 'The soupsieve package is not installed. CSS selectors cannot be used.' Installing the soupsieve package with pip did not resolve the issue.

**Comment by Sandmann79** [comment]
Please try the solution provided here: https://github.com/Sandmann79/xbmc/issues/550#issuecomment-803996317

**Comment by Netspider** [comment]
BS4.6.2 helped for me so I could at least login for a short time.

**Comment by yannos** [comment]
Seeing the same issue.
BS was already 4.6.2 and kodi wouldn't let me uninstall due to dependencies. I manually installed it and it logged in but couldn't watch anything due to "Prime Video error". I will paste a log later but seems the addon is broken at the moment either due to changes by Prime or package versions.

(Obligatory thanks for your work and the addon - it was one of the essentials for me to access my prime video account for content)

**Comment by Sandmann79** [comment]
Please check, if you have all Addon v0.9.2 installed and report back.

**Comment by pluschpups** [comment]
No, but that was the right hint. I wondered, that it would not update. The only available version was 0.9.1. So i just now deinstalled the plugin and deleted the repository. Then I reinstalled the repo and the version 0.9.2 was available. Now it works as before.

**Comment by vendetta1987** [comment]
After updating to 0.9.2 by means of forcing the repo to search for updates, I still get the error. Even after removing the previous version and settings it won't work. While installing the latest version Kodi tells me all dependencies are met already.

> Beautiful soup 4 4.6.2
> Mechanical soup 0.12.0
> Soup sieve 1.9.6

My system is running Kodi 18.7 on an RPi 4B.
The following is a log of my login attempt:
`2021-03-30 21:28:22.088 T:2290208976  NOTICE: [Amazon VOD] Connect to SignIn Page 5 attempts left
2021-03-30 21:28:25.018 T:2290208976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NotImplementedError'>
                                            Error Contents: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 102, in EntryPoint
                                                exec('{}()'.format(mode))
                                              File "<string>", line 1, in <module>
                                              File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 582, in LogIn
                                                form = br.select_form('form[name="signIn"]')
                                              File "/home/kodi/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 215, in select_form
                                                limit=nr + 1)
                                              File "/home/kodi/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 1871, in select
                                                "Cannot execute CSS selectors because the soupsieve package is not installed."
                                            NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            -->End of Python script error report<--
2021-03-30 21:28:25.162 T:2290208976 WARNING: CPythonInvoker(123, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE`

**Comment by Sandmann79** [comment]
With BS4 4.6.2 from offical Kodi repo this shouldn't happen, these version has soupsieve included.
Starting with BS4 v4.7 they removed soupsieve and you have to install soupsieve 1.9.6+leia.1 to get it working. 
Maybe you have it installed from another repo.

**Comment by cptncrnch** [comment]
I installed Addon v0.9.2 and confirmed BS 4.6.2 was installed already. I entered my login information and entered the OTP code, but got the Unknown error again.

Here's my log after reinstalling Addon v0.9.2 and trying to log in: https://pastebin.com/XnANy3gX

Errors:

1. 2021-03-30 17:03:06.505 T:1030746336   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2. 2021-03-30 17:04:26.787 T:1916548016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
3. 2021-03-30 17:09:10.614 T:1120923872   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
4. 2021-03-30 17:09:10.617 T:1916548016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed

**Comment by cptncrnch** [comment]
I seem to be able to get to the OTP step (I assume only if you have 2FA enabled on your Amazon account) if I attempt logging in after an unsuccessful login attempt with the Unknown error. However, afterwards there's a CAPTCHA step where I'm unable to submit OK after entering text in the CAPTCHA field. Pressing the center button on my remote or the Enter key on the keyboard keeps opening the onscreen keyboard because the text entry field is selected. Pressing the down arrow on my remote or the Tab or arrow keys on the keyboard doesn't move the selection to the OK button.

**Comment by yannos** [comment]
> @yannos strange that BS4 4.9.3 and SV 1.9.6+leia.1 not works for you, on my testsystems these combination works fine.
> To the second log: Is your account UK based?

Yes strange it can't see soupseive.

Yes account is UK based. I have tried the addon with region set to "ROE Europe" and UK.

**Comment by Netspider** [comment]
> 
> 
> @yannos strange that BS4 4.9.3 and SV 1.9.6+leia.1 not works for you, on my testsystems these combination works fine.
> To the second log: Is your account UK based?

I tried reinstalling amazon-vod and the dependencies and also get the soupsieve-missing-error when installing with a german account:
> plugin.video.amazon-test v0.9.2
> BS4 v4.9.3
> soupseive v1.9.6+leia.1
> Mechanicalsoup v1.0.0

**Comment by Sandmann79** [comment]
@yannos UK is the correct region setting for you. It's important to save the settings after changing the region, reopen settings and login again. It's impossible that the primevideo error appear, if UK as region is set.

@Netspider you can always downgrade BS4. It's like i wrote above - on my systems it works.
Just for clarification: this issue is related to the Kodi Repo and it should have been fixed with this PR:  https://github.com/xbmc/repo-scripts/pull/1944

**Comment by cptncrnch** [comment]
> @cptncrnch if you get an unknown error message while logging in, you should do the displayed steps, login again and provide the mentioned files here.
> ~I recently checked the Captcha form and by pressing down key it jumps to the OK button.~
> Btw. according to your log you have BS4 v4.9.3 installed, but this isn't the problem here.
> 
> edit: i checked the wrong captcha dialog - you're right there is no navigation possible. Fixed with [0e33ec6](https://github.com/Sandmann79/xbmc/commit/0e33ec61f7a442859533d29275b0e3de380de76f).

@Sandmann79 all fixed now. I rebooted for good measure today and was able to log in. No CAPTCHA step this time. I was stuck at a loading animation that didn't seem to be going anywhere after logging in so I hit back and opened the Addon again and was able to see the main menu with my name logged in. Thanks for working on this great Addon!

**Comment by yannos** [comment]
@Sandmann79 so I did a fresh install of the addon, assigned the region and played with the dependencies and it now works. The dependency combination that worked for me was:
```
plugin.video.amazon-test v0.9.2
BS4 v4.6.2 
soupseive v1.9.6+leia.1
```
With bs4 v4.9.3 it couldn't log in.

Thanks for your help

**Comment by Netspider** [comment]
same for me, it is now working with bs 4.6.2 and amazon 0.9.2.

**Comment by vendetta1987** [comment]
I managed to make it work again by installing BS4 4.6.2 from zip. However even though video streaming works I'm now facing #555 which also complains about BS4 not being present.

**Comment by emc02** [comment]
can also confirm that it works with bs4.6.2 on Kodi18, but on Kodi19 it's not possible to use bs4.6.2 because it's py2...
Is there any (dirty) fix for Kodi19?

**Comment by Sandmann79** [comment]
@emc02 on matrix there's bs4 4.6.3 available here: https://mirrors.kodi.tv/addons/matrix/script.module.beautifulsoup4/
Providing a fix is impossible, because that's not an addon issue - it's an issue with BS4.

**Comment by emc02** [comment]
Thanks for the fast reply, it works with 4.6.3 (but I can't find the option to disable automatic updates of the plugin in Kodi19...) But that's no problem, I can reinstall it if needed.
Hopefully they will fix the problem with the bs4 plugin...

**Comment by Tr1aX** [comment]
Just in case somebody is having the same login issues as I had on a raspberry PI, LibreELEC and Kodi Leia.
After reading this trhead I fixed it by doing this:

Go to Configuration - System - Addons - Manage dependencies (or smt like that)
Search for BeautifulSoup4, select it, disable auto-update, select Update and from there choose version 4.5.3 from caché.

Hope this helps somebody!

**Comment by bstabens** [comment]
I have the same problem, but I can't solve it by downgrading BS4. I'm not allowed to because it is used by MechanicalSoup, which I in turn also can't downgrade/deinstall/reinstall because it is used by BeautifulSoup4...
I already tried to deactivate automatic updates, removing Amazon, removing Sandman repo and reinstalling everything. Still no luck. Would be happy to get pointers how to fix it.
[kodi.log](https://github.com/Sandmann79/xbmc/files/6896061/kodi.log)

**Comment by MrJollyOlliMan** [comment]
I still have the same error in my log files:
`/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used. 'The soupsieve package is not installed. CSS selectors cannot be used.'`
My add on version are:
Amazon VOP v0.9.4
BS4 is v4.9.3.
SoupSieve v1.9.6+leia.1
A downgrade to BS4 v4.5.3 or v4.6.3 isn't possible neither in Kodi AddOns nor by hand. Has anyone a hint what I could do?

**Comment by tmoriki** [comment]
Hi @MrJollyOlliMan, I got the same error too.
I have installed same version of addons and kodi version 18.7 on raspbian OS. (buster)

In my kodi environment, it seems to failed install the soupsieve package.
(if successed, *.pyc files should be created at import time. But NOT all *pyc files are there.)

<pre>
pi@raspberrypi:~/.kodi/addons/script.module.soupsieve/lib $ ls -l soupsieve/
total 204
-rw-r--r-- 1 pi pi  4130 Feb  5 09:30 __init__.py
-rw-r--r-- 1 pi pi  5145 Feb  5 10:03 __init__.pyc
-rw-r--r-- 1 pi pi  6621 Feb  5 09:30 __meta__.py
-rw-r--r-- 1 pi pi  6513 Feb  5 10:03 __meta__.pyc
-rw-r--r-- 1 pi pi 53558 Feb  5 09:30 css_match.py
-rw-r--r-- 1 pi pi 43289 Feb  5 09:30 css_parser.py
-rw-r--r-- 1 pi pi 31919 Feb  5 10:03 css_parser.pyc
-rw-r--r-- 1 pi pi  8706 Feb  5 09:30 css_types.py
-rw-r--r-- 1 pi pi  4358 Feb  5 09:30 util.py
-rw-r--r-- 1 pi pi  4912 Feb  5 10:03 util.pyc
</pre>

Then I have tested import soupsieve packages on interactive command-line, I saw further error messages.
Is it helpful for anyone?

<pre>
pi@raspberrypi:~/.kodi/addons/script.module.soupsieve/lib $ ln -s ../../script.module.backports.functools_lru_cache/lib/backports .
backports@  soupsieve/
pi@raspberrypi:~/.kodi/addons/script.module.soupsieve/lib $ ls -lF
total 8
lrwxr-xr-x 1 pi pi   63 Feb  5 10:17 backports -> ../../script.module.backports.functools_lru_cache/lib/backports/
drwxr-xr-x 2 pi pi 4096 Feb  5 10:03 soupsieve/
pi@raspberrypi:~/.kodi/addons/script.module.soupsieve/lib $ python2
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'version' is not defined
>>> import backports
>>> import soupsieve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "soupsieve/__init__.py", line 30, in <module>
    from . import css_parser as cp
  File "soupsieve/css_parser.py", line 4, in <module>
    from . import util
  File "soupsieve/util.py", line 23, in <module>
    from backports.functools_lru_cache import lru_cache  # noqa F401
ImportError: No module named functools_lru_cache
>>> 
</pre>

Then... I'll try replace soupsieve package by my hand. ;-)

**Comment by MrJollyOlliMan** [comment]
Hi @[tmoriki](https://github.com/tmoriki),

I tried to go thru the same way as you show above. Initial there are no *.pyc files available.
```
LibreELEC:~/.kodi/addons/script.module.soupsieve/lib/soupsieve # ls -l
total 122
-rw-r--r--    1 root     root          4130 Mar 20  2021 __init__.py
-rw-r--r--    1 root     root          6621 Mar 20  2021 __meta__.py
-rw-r--r--    1 root     root         53558 Mar 20  2021 css_match.py
-rw-r--r--    1 root     root         43289 Mar 20  2021 css_parser.py
-rw-r--r--    1 root     root          8706 Mar 20  2021 css_types.py
-rw-r--r--    1 root     root          4358 Mar 20  2021 util.py
```

```
LibreELEC:~/.kodi/addons/script.module.soupsieve/lib # ln -s ../../script.module.backports.functools_lru_cache/li
b/backports
LibreELEC:~/.kodi/addons/script.module.soupsieve/lib # ls -l
total 2
lrwxrwxrwx    1 root     root            63 Feb  7 07:46 backports -> ../../script.module.backports.functools_lru_cache/lib/backports
drwxr-xr-x    2 root     root          1024 Feb  7 07:39 soupsieve
```

LibreELEC might use optimized settings for python. But I get no further error and all *.pyo files are available.
```
LibreELEC:~/.kodi/addons/script.module.soupsieve/lib # python2
Python 2.7.16 (default, Jul  6 2021, 19:29:10)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import backports
>>> import soupsieve
>>>
>>> exit()
LibreELEC:~/.kodi/addons/script.module.soupsieve/lib # cd soupsieve/
LibreELEC:~/.kodi/addons/script.module.soupsieve/lib/soupsieve # ls -l
total 224
-rw-r--r--    1 root     root          4130 Mar 20  2021 __init__.py
-rw-r--r--    1 root     root          5145 Feb  7 07:39 __init__.pyo
-rw-r--r--    1 root     root          6621 Mar 20  2021 __meta__.py
-rw-r--r--    1 root     root          6513 Feb  7 07:39 __meta__.pyo
-rw-r--r--    1 root     root         53558 Mar 20  2021 css_match.py
-rw-r--r--    1 root     root         40838 Feb  7 07:47 css_match.pyo
-rw-r--r--    1 root     root         43289 Mar 20  2021 css_parser.py
-rw-r--r--    1 root     root         31919 Feb  7 07:39 css_parser.pyo
-rw-r--r--    1 root     root          8706 Mar 20  2021 css_types.py
-rw-r--r--    1 root     root         12023 Feb  7 07:47 css_types.pyo
-rw-r--r--    1 root     root          4358 Mar 20  2021 util.py
-rw-r--r--    1 root     root          4912 Feb  7 07:39 util.pyo
```

How did you install soupsieve by hand, with pip?

**Comment by Varstahl** [comment]
Soupsieve should technically not be installed, because it's automatically embedded within proper releases of BS4. IIRC you could just try to manually remove/move somewhere else `~/.kodi/addons/script.module.beautifulsoup4` and `~/.kodi/addons/script.module.mechanicalsoup`, and restarting Kodi. At that point you should be able to go to our repo and install them from there, making sure you have the correct repo selected.

**Comment by Varstahl** [comment]
> Pip command makes no help, I don't know WHY

They're not pure python modules, those are python modules built to work inside Kodi itself, so simply adding them to your local python installation won't do. Glad you got this solved, though.

**Comment by MrJollyOlliMan** [comment]
Hi @[Varstahl](https://github.com/Varstahl),

today I spent some hours for my media center machine, unfortunately without success.

I removed `script.module.beautifulsoup4` and `script.module.mechanicalsoup` from addon directory: `~/.kodi/addons` and installed your ones. --> Same Error as reported above.

Is there a way to install a python module from a selected repo? I had to use the *.zip installation.
