### ISSUE TITLE
Watchlist no longer works with web_api

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#775]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.1.4

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Linux, Android
- OS version:
- Kodi version number: 19.4

**Upload Logs**
```

2025-03-09 13:13:43.283 T:7031     INFO <general>: [Amazon VOD] network.py:119 getURL: https://www.primevideo.com/gp/video/api/paginateCollection?serviceToken=v0_Cl0KJGY0ZGQ5MzQ4LWNiMDgtNDYzZS1iN2E1LTIwNzU5MjBlNDM5MxCQtMzW1zIaLDEyeTh4VHpRampQcGRMYWM1b3VOT1VPYysxc3BJSklVek5tRmh1cFBESFU9IAESBWhwYWdlGAAyBmNlbnRlckA5SiQzZTlhNmM3YS1jOWI0LTRjZWEtYjQyMS1kNjVhMDNhMWFkNjNaCQoFTU9WSUUSAHoAggG5AxIqMToxMk9MU0FBQ1BNMUNPNyMjTVpRV0daTFVNVlNFR1lMU041MlhHWkxNMABQFGKEA-2Qpe-Sz5-aGMuC9se77JnEoAGIibW-5K3C0lqX-Lu1mYj1q7gB5J-N_rmdl56dAeuv7fvPktLXmgHb5bnMua-32CzE4svC-KK1n5gB5J3Zk_PWneOSAZOUhp3Jz-n4uAHJibW2jfam7EiovvysjrbM3I4B9qXw2s2E49d2h-z39KiOr5xTjJaJj6vNz4pV9vLP_d_R-PyJAb6GqZm_-5X-kwGxwPLuq5LSva8ByICq9NGkkt2kAbr2192A1MaBsgHXkO2gjsf8sCKy27Glzd_oyr4BtImp_Ju_8dpog8Wty7jNx8-dAaCIpabZw9PlELmygIj1iLSGrgHVlrHN_pHxrdwB4viR_N_t_OmtAY-Koa-4wpTugQG_muSku5PJy6kBi4zJotvfvJagAfqbnbKvivPyjQGmlc28zpSEjQe84OjSqKvGh6ABr6bZkaT_qN2KAfLn6sTh69_09gGNlMm0rfiOieYBlPaS5peZoeGdAayD9Ze84cmLEfilufnavZKchgFwOQ%3D%3D&startIndex=20&paginationTargetId=V2%3D4AEA6u69gYPeuYe-toZwYWdlSWSIcGFnZVR5cGWMY29sbGVjdGlvbklkiHdpZGdldElkjo5zd2lmdElkVmVyc2lvbt7EiolXYXRjaGxpc3SLhGhvbWWMjqoxOjEyT0xTQUFDUE0xQ083IyNNWlFXR1pMVU1WU0VHWUxTTjUyWEdaTE2ND46CVjI%3D&pageSize=20&pageType=browse&pageId=default&variant=desktopWindows&actionScheme=default&payloadScheme=default&decorationScheme=web-search-decoration-tournaments-v2&featureScheme=web-search-v4&dynamicFeatures=HorizontalPagination&widgetScheme=web-explorecs-v11&collectionType=Container
2025-03-09 13:13:43.291 T:6973    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2025-03-09 13:13:43.690 T:7031     INFO <general>: [Amazon VOD] logging.py:57 Saved Log with filename “html-183.log”
2025-03-09 13:13:43.690 T:7031     INFO <general>: [Amazon VOD] network.py:208 Download Time: 0.40721145799989245
2025-03-09 13:13:43.702 T:7031     INFO <general>: [Amazon VOD] logging.py:80 Saved JSON data with filename “20250309_131343692249_22.json”
2025-03-09 13:13:43.704 T:7031    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeDecodeError'>
                                                   Error Contents: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
                                                   Traceback (most recent call last):
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1439, in _LazyLoad
                                                       seeMore = cnt['viewOutput']['features'][wl_lib]['content']
                                                   KeyError: 'viewOutput'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 185, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 459, in Browse
                                                       node, breadcrumb = self._TraverseCatalog(path)
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 155, in _TraverseCatalog
                                                       self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                                     File "/home/paco/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1454, in _LazyLoad
                                                       t = json.loads(base64.b64decode(q['serviceToken']))
                                                     File "/usr/lib/python3.10/json/__init__.py", line 341, in loads
                                                       s = s.decode(detect_encoding(s), 'surrogatepass')
                                                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
                                                   -->End of Python script error report<--
                                                   
```

**Describe the bug**

This happens when going to my space, my list, movies.

**Comment by Sandmann79** [comment]
This error should be fixed with Commit d7cd024e4bf9b9ed6f77005fdb1f950ec0e7bd15. 
Please test and give a short feedback.

**Comment by GG-76** [comment]
Isn't this the same problem I already assigned in November? https://github.com/Sandmann79/xbmc/issues/759

**Comment by baby-scarf** [comment]
Good morning,

I have the same error on kodi 20.5 on raspberry 4, it tries to load the movie page and then error see log, I modified the web_api.py file without success it still doesn't work...

Can you help me find a solution

Thank you very much

**Comment by cpassuel** [comment]
There is an exception TypeError: Incorrect padding on the  t = json.loads(base64.b64decode(q['serviceToken'])) line
Seems it is a malformed b64 string.

**Comment by cpassuel** [comment]
q['serviceToken'] contains - and _. I tried urlsafe_b64decode without success
BTW I use LibreElec 9.2.8

**Comment by Sandmann79** [comment]
@GG-76 No, a clear error message is displayed here, whereas this is not the case in your issue.

@baby-scarf @cpassuel i have updated the above commit with an wider exception clause: a2af27b3cc2481139da548e0430a6170c9bcde0c. Should now work

**Comment by cpassuel** [comment]
I tried the latest version of the repo and it's working well on my LibreElec 9.2.8

**Comment by baby-scarf** [comment]
Hello, just to thank you for your work and especially your speed, this time it works perfectly. See you soon. (kodi 20.5) "a2af27b"

**Comment by Spliff58** [comment]
Thanks for the quick response. All seems to work now.
